Repository IEEE-CS-Society/ieee-cs-srm-v2, pull requests merged in 2024-10, with the labels that each got.

#1 Feat: Added Folders
  client/README.md
  server/README.md
Labels: enhancement

#6 Feat: Login Added
  .DS_Store
  .idea/.gitignore
  .idea/ieee-cs-srm-v2.iml
  .idea/modules.xml
  .idea/vcs.xml
  client/.DS_Store
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/assets/IEEE-CS_LogoTM-black.png
  client/src/assets/IEEE-CS_LogoTM-orange.png
  client/src/assets/IEEE-CS_LogoTM-white.png
  client/src/components/Login/LoginPage.js
  client/src/components/Login/SignupPage.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/reportWebVitals.js
  client/src/setupTests.js
  client/tailwind.config.js
Labels: enhancement

#8 updated files
  README.md
  server/credentials.env
  server/main.py
Labels: Backend

#10 Added offer page and students' testimonials
  client/offer/.gitignore
  client/offer/README.md
  client/offer/package-lock.json
  client/offer/package.json
  client/offer/postcss.config.js
  client/offer/public/favicon.ico
  client/offer/public/index.html
  client/offer/public/logo192.png
  client/offer/public/logo512.png
  client/offer/public/manifest.json
  client/offer/public/robots.txt
  client/offer/src/App.css
  client/offer/src/App.js
  client/offer/src/App.test.js
  client/offer/src/components/BrandingCard.js
  client/offer/src/components/DigitalMarketingCard.js
  client/offer/src/components/MobileAppCard.js
  client/offer/src/components/SeoCard.js
  client/offer/src/components/Testimonials.js
  client/offer/src/components/UserTestingCard.js
  client/offer/src/components/WebDevCard.js
  client/offer/src/images/brand.svg
  client/offer/src/images/digital.svg
  client/offer/src/images/mobile.svg
  client/offer/src/images/seo.svg
  client/offer/src/images/user.svg
  client/offer/src/images/web.svg
  client/offer/src/index.css
  client/offer/src/index.js
  client/offer/src/logo.svg
  client/offer/src/reportWebVitals.js
  client/offer/src/setupTests.js
  client/offer/src/testimonials/1.svg
  client/offer/src/testimonials/2.svg
  client/offer/src/ui/3d-card.js
  client/offer/tailwind.config.js
Labels: Frontend

#11 new api
  server/credentials.env
  server/main.py
Labels: Backend

#12 Fixed the offer page, login page
  .DS_Store
  client/.DS_Store
  client/src/App.css
  client/src/App.js
  client/src/assets/images/brand.svg
  client/src/assets/images/digital.svg
  client/src/assets/images/mobile.svg
  client/src/assets/images/seo.svg
  client/src/assets/images/user.svg
  client/src/assets/images/web.svg
  client/src/assets/testimonials/1.svg
  client/src/assets/testimonials/2.svg
  client/src/assets/ui/3d-card.js
  client/src/components/Login/LoginPage.js
  client/src/components/Login/SignupPage.js
  client/src/components/Offer/BrandingCard.js
  client/src/components/Offer/DigitalMarketingCard.js
  client/src/components/Offer/MobileAppCard.js
  client/src/components/Offer/SeoCard.js
  client/src/components/Offer/Testimonials.js
  client/src/components/Offer/UserTestingCard.js
  client/src/components/Offer/WebDevCard.js
  client/src/components/cards/ui/3d-card.js
  client/src/index.css
Labels: Frontend

#13 Events backend
  server/testevent.py
Labels: Backend

#14 EventPage
  client/src/App.js
  client/src/assets/events/IoT.jpg
  client/src/assets/events/ai.jpg
  client/src/assets/events/boot.jpg
  client/src/assets/events/cyber.jpg
  client/src/assets/events/hackathon.jpg
  client/src/assets/events/tech.jpg
  client/src/components/Events/AnimatedBackground.js
  client/src/components/Events/EventCard.js
  client/src/components/Events/EventGrid.js
  client/src/components/Events/EventModal.js
  client/src/components/Events/Events.css
  client/src/components/Events/Events.js
  client/src/components/Events/RegistrationForm.js
Labels: enhancement

#15 Mass mailing
  server/IEEE-CS_LogoTM-white.png
  server/credentials.env
  server/massmailing.py
Labels: Backend

#18 Updated password and all
  server/main.py
  server/requirements.txt
Labels: Backend

#19 Event page updated
  client/src/App.js
  client/src/components/Events/AnimatedBackground.js
  client/src/components/Events/EventCard.js
  client/src/components/Events/EventGrid.js
  client/src/components/Events/EventModal.js
  client/src/components/Events/Events.css
  client/src/components/Events/Events.js
  client/src/components/Events/RegistrationForm.js
  client/src/components/Homepage/Events.js
  client/src/components/Homepage/Header.js
  server/main.py
Labels: enhancement

#20 fixed events stuff
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/src/App.js
  client/src/assets/akshit.svg
  client/src/assets/trex.svg
  client/src/components/Homepage/Events.js
  client/src/components/Homepage/footer.js
  client/tailwind.config.js
Labels: enhancement

#21 Server : Configured and Hosted with Conn to the Client
  client/src/components/Homepage/Events.js
  server/main.py
  server/requirements.txt
Labels: Backend, Frontend

#22 Edit profile page
  client/src/assets/images/bg.jpg
  client/src/assets/images/mobiledevices.jpg
  client/src/assets/logo/logo.png
  client/src/components/Edit Profile/app.jsx
Labels: enhancement

#23 Feat: Updated the Repo
  client/src/components/Homepage/Events.js
  client/src/components/Login/LoginPage.js
  client/src/components/Login/SignupPage.js
  server/main.py
Labels: bug, enhancement, Backend, Frontend

#24 Fix: Server emailing fixed
  server/main.py
Labels: enhancement, Backend

#25 mail template
  server/main.py
Labels: Backend
